//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquardensUnitTest.wsListini {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEsito", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcCategorieElencoEsito))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcEsitoIdBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcListiniElencoEsito))]
    public partial class dcEsito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EsitoCodiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsitoDescrizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EsitoNotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EsitoCodice {
            get {
                return this.EsitoCodiceField;
            }
            set {
                if ((this.EsitoCodiceField.Equals(value) != true)) {
                    this.EsitoCodiceField = value;
                    this.RaisePropertyChanged("EsitoCodice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoDescriz {
            get {
                return this.EsitoDescrizField;
            }
            set {
                if ((object.ReferenceEquals(this.EsitoDescrizField, value) != true)) {
                    this.EsitoDescrizField = value;
                    this.RaisePropertyChanged("EsitoDescriz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EsitoNota {
            get {
                return this.EsitoNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.EsitoNotaField, value) != true)) {
                    this.EsitoNotaField = value;
                    this.RaisePropertyChanged("EsitoNota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategorieElencoEsito", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcCategorieElencoEsito : AquardensUnitTest.wsListini.dcEsito {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcCategoria[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcCategoria[] Elenco {
            get {
                return this.ElencoField;
            }
            set {
                if ((object.ReferenceEquals(this.ElencoField, value) != true)) {
                    this.ElencoField = value;
                    this.RaisePropertyChanged("Elenco");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcEsitoIdBox", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcEsitoIdBox : AquardensUnitTest.wsListini.dcEsito {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListiniElencoEsito", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcListiniElencoEsito : AquardensUnitTest.wsListini.dcEsito {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcListino[] ElencoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcListino[] Elenco {
            get {
                return this.ElencoField;
            }
            set {
                if ((object.ReferenceEquals(this.ElencoField, value) != true)) {
                    this.ElencoField = value;
                    this.RaisePropertyChanged("Elenco");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListino", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcListinoCompleto))]
    public partial class dcListino : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AccontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcComponenteInfo ComponenteInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DisponibilitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdVoucherScadenzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImmagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpiantoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPrenotabileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsSingleSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcIva IvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcTariffa TariffaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestoAggiuntivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Acconto {
            get {
                return this.AccontoField;
            }
            set {
                if ((this.AccontoField.Equals(value) != true)) {
                    this.AccontoField = value;
                    this.RaisePropertyChanged("Acconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcComponenteInfo ComponenteInfo {
            get {
                return this.ComponenteInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComponenteInfoField, value) != true)) {
                    this.ComponenteInfoField = value;
                    this.RaisePropertyChanged("ComponenteInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Disponibilita {
            get {
                return this.DisponibilitaField;
            }
            set {
                if ((this.DisponibilitaField.Equals(value) != true)) {
                    this.DisponibilitaField = value;
                    this.RaisePropertyChanged("Disponibilita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdVoucherScadenza {
            get {
                return this.IdVoucherScadenzaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdVoucherScadenzaField, value) != true)) {
                    this.IdVoucherScadenzaField = value;
                    this.RaisePropertyChanged("IdVoucherScadenza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Immagine {
            get {
                return this.ImmagineField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmagineField, value) != true)) {
                    this.ImmagineField = value;
                    this.RaisePropertyChanged("Immagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto {
            get {
                return this.ImpiantoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpiantoField, value) != true)) {
                    this.ImpiantoField = value;
                    this.RaisePropertyChanged("Impianto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPrenotabile {
            get {
                return this.IsPrenotabileField;
            }
            set {
                if ((this.IsPrenotabileField.Equals(value) != true)) {
                    this.IsPrenotabileField = value;
                    this.RaisePropertyChanged("IsPrenotabile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSingleSale {
            get {
                return this.IsSingleSaleField;
            }
            set {
                if ((this.IsSingleSaleField.Equals(value) != true)) {
                    this.IsSingleSaleField = value;
                    this.RaisePropertyChanged("IsSingleSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcIva Iva {
            get {
                return this.IvaField;
            }
            set {
                if ((object.ReferenceEquals(this.IvaField, value) != true)) {
                    this.IvaField = value;
                    this.RaisePropertyChanged("Iva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcTariffa Tariffa {
            get {
                return this.TariffaField;
            }
            set {
                if ((object.ReferenceEquals(this.TariffaField, value) != true)) {
                    this.TariffaField = value;
                    this.RaisePropertyChanged("Tariffa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestoAggiuntivo {
            get {
                return this.TestoAggiuntivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TestoAggiuntivoField, value) != true)) {
                    this.TestoAggiuntivoField = value;
                    this.RaisePropertyChanged("TestoAggiuntivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategoria", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImmagineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpiantoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestoAggiuntivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Immagine {
            get {
                return this.ImmagineField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmagineField, value) != true)) {
                    this.ImmagineField = value;
                    this.RaisePropertyChanged("Immagine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto {
            get {
                return this.ImpiantoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpiantoField, value) != true)) {
                    this.ImpiantoField = value;
                    this.RaisePropertyChanged("Impianto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestoAggiuntivo {
            get {
                return this.TestoAggiuntivoField;
            }
            set {
                if ((object.ReferenceEquals(this.TestoAggiuntivoField, value) != true)) {
                    this.TestoAggiuntivoField = value;
                    this.RaisePropertyChanged("TestoAggiuntivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdBox", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.InfoBox))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcIva))]
    public partial class IdBox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdEsternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdEsterno {
            get {
                return this.IdEsternoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdEsternoField, value) != true)) {
                    this.IdEsternoField = value;
                    this.RaisePropertyChanged("IdEsterno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoBox", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AquardensUnitTest.wsListini.dcIva))]
    public partial class InfoBox : AquardensUnitTest.wsListini.IdBox {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcIva", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcIva : AquardensUnitTest.wsListini.InfoBox {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AliquotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Aliquota {
            get {
                return this.AliquotaField;
            }
            set {
                if ((this.AliquotaField.Equals(value) != true)) {
                    this.AliquotaField = value;
                    this.RaisePropertyChanged("Aliquota");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcComponenteInfo", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcComponenteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.InfoBox CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantitaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.InfoBox Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantita {
            get {
                return this.QuantitaField;
            }
            set {
                if ((this.QuantitaField.Equals(value) != true)) {
                    this.QuantitaField = value;
                    this.RaisePropertyChanged("Quantita");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcTariffa", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcTariffa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescrizioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdTariffaListinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImportoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ScontoAbilitatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descrizione {
            get {
                return this.DescrizioneField;
            }
            set {
                if ((object.ReferenceEquals(this.DescrizioneField, value) != true)) {
                    this.DescrizioneField = value;
                    this.RaisePropertyChanged("Descrizione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox IdTariffaListino {
            get {
                return this.IdTariffaListinoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTariffaListinoField, value) != true)) {
                    this.IdTariffaListinoField = value;
                    this.RaisePropertyChanged("IdTariffaListino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importo {
            get {
                return this.ImportoField;
            }
            set {
                if ((this.ImportoField.Equals(value) != true)) {
                    this.ImportoField = value;
                    this.RaisePropertyChanged("Importo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ScontoAbilitato {
            get {
                return this.ScontoAbilitatoField;
            }
            set {
                if ((this.ScontoAbilitatoField.Equals(value) != true)) {
                    this.ScontoAbilitatoField = value;
                    this.RaisePropertyChanged("ScontoAbilitato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListinoCompleto", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcListinoCompleto : AquardensUnitTest.wsListini.dcListino {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcListinoFilter", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcListinoFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DatiAggiuntiviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdBeachMapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdListinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdPersonaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox[] IdTariffeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsGiornoFestivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TariffaRichiestaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] TipiListiniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoPagamentoPrenotazioneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtenzaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi {
            get {
                return this.DatiAggiuntiviField;
            }
            set {
                if ((this.DatiAggiuntiviField.Equals(value) != true)) {
                    this.DatiAggiuntiviField = value;
                    this.RaisePropertyChanged("DatiAggiuntivi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdBeachMap {
            get {
                return this.IdBeachMapField;
            }
            set {
                if ((object.ReferenceEquals(this.IdBeachMapField, value) != true)) {
                    this.IdBeachMapField = value;
                    this.RaisePropertyChanged("IdBeachMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCategoriaField, value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox IdListino {
            get {
                return this.IdListinoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdListinoField, value) != true)) {
                    this.IdListinoField = value;
                    this.RaisePropertyChanged("IdListino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox IdPersonale {
            get {
                return this.IdPersonaleField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPersonaleField, value) != true)) {
                    this.IdPersonaleField = value;
                    this.RaisePropertyChanged("IdPersonale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox[] IdTariffe {
            get {
                return this.IdTariffeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdTariffeField, value) != true)) {
                    this.IdTariffeField = value;
                    this.RaisePropertyChanged("IdTariffe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsGiornoFestivo {
            get {
                return this.IsGiornoFestivoField;
            }
            set {
                if ((this.IsGiornoFestivoField.Equals(value) != true)) {
                    this.IsGiornoFestivoField = value;
                    this.RaisePropertyChanged("IsGiornoFestivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TariffaRichiesta {
            get {
                return this.TariffaRichiestaField;
            }
            set {
                if ((this.TariffaRichiestaField.Equals(value) != true)) {
                    this.TariffaRichiestaField = value;
                    this.RaisePropertyChanged("TariffaRichiesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] TipiListini {
            get {
                return this.TipiListiniField;
            }
            set {
                if ((object.ReferenceEquals(this.TipiListiniField, value) != true)) {
                    this.TipiListiniField = value;
                    this.RaisePropertyChanged("TipiListini");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TipoPagamentoPrenotazione {
            get {
                return this.TipoPagamentoPrenotazioneField;
            }
            set {
                if ((this.TipoPagamentoPrenotazioneField.Equals(value) != true)) {
                    this.TipoPagamentoPrenotazioneField = value;
                    this.RaisePropertyChanged("TipoPagamentoPrenotazione");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Utenza {
            get {
                return this.UtenzaField;
            }
            set {
                if ((object.ReferenceEquals(this.UtenzaField, value) != true)) {
                    this.UtenzaField = value;
                    this.RaisePropertyChanged("Utenza");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseRequest", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcBaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImpiantoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.dcBaseLanguage LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Impianto {
            get {
                return this.ImpiantoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImpiantoField, value) != true)) {
                    this.ImpiantoField = value;
                    this.RaisePropertyChanged("Impianto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.dcBaseLanguage Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIdField, value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcBaseLanguage", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcBaseLanguage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IetfLanguageTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TwoLetterISOLanguageNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IetfLanguageTag {
            get {
                return this.IetfLanguageTagField;
            }
            set {
                if ((object.ReferenceEquals(this.IetfLanguageTagField, value) != true)) {
                    this.IetfLanguageTagField = value;
                    this.RaisePropertyChanged("IetfLanguageTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TwoLetterISOLanguageName {
            get {
                return this.TwoLetterISOLanguageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TwoLetterISOLanguageNameField, value) != true)) {
                    this.TwoLetterISOLanguageNameField = value;
                    this.RaisePropertyChanged("TwoLetterISOLanguageName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcCategoriaFilter", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcCategoriaFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DatiAggiuntiviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi {
            get {
                return this.DatiAggiuntiviField;
            }
            set {
                if ((this.DatiAggiuntiviField.Equals(value) != true)) {
                    this.DatiAggiuntiviField = value;
                    this.RaisePropertyChanged("DatiAggiuntivi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dcComponentiPacchettoRequest", Namespace="http://zitaca.com/gridservices")]
    [System.SerializableAttribute()]
    public partial class dcComponentiPacchettoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DatiAggiuntiviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AquardensUnitTest.wsListini.IdBox IdPacchettoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DatiAggiuntivi {
            get {
                return this.DatiAggiuntiviField;
            }
            set {
                if ((this.DatiAggiuntiviField.Equals(value) != true)) {
                    this.DatiAggiuntiviField = value;
                    this.RaisePropertyChanged("DatiAggiuntivi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AquardensUnitTest.wsListini.IdBox IdPacchetto {
            get {
                return this.IdPacchettoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPacchettoField, value) != true)) {
                    this.IdPacchettoField = value;
                    this.RaisePropertyChanged("IdPacchetto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/002", ConfigurationName="wsListini.iElenchi_002")]
    public interface iElenchi_002 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListini", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListini", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorie", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorieResponse")]
        AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcCategoriaFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorie", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetCategorieResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcCategoriaFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovo", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovoRespo" +
            "nse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetListiniCompatibiliRinnovo(AquardensUnitTest.wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovo", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetListiniCompatibiliRinnovoRespo" +
            "nse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniCompatibiliRinnovoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchetto", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchettoResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetComponentiPacchetto(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcComponentiPacchettoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchetto", ReplyAction="http://zitaca.com/gridservices/002/iElenchi_002/GetComponentiPacchettoResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetComponentiPacchettoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcComponentiPacchettoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iElenchi_002Channel : AquardensUnitTest.wsListini.iElenchi_002, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iElenchi_002Client : System.ServiceModel.ClientBase<AquardensUnitTest.wsListini.iElenchi_002>, AquardensUnitTest.wsListini.iElenchi_002 {
        
        public iElenchi_002Client() {
        }
        
        public iElenchi_002Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iElenchi_002Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchi_002Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchi_002Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListini(@base, filter);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListiniAsync(@base, filter);
        }
        
        public AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcCategoriaFilter filter) {
            return base.Channel.GetCategorie(@base, filter);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcCategoriaFilter filter) {
            return base.Channel.GetCategorieAsync(@base, filter);
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetListiniCompatibiliRinnovo(AquardensUnitTest.wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione) {
            return base.Channel.GetListiniCompatibiliRinnovo(@base, tipoListino, idIscrizione);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniCompatibiliRinnovoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, int tipoListino, string idIscrizione) {
            return base.Channel.GetListiniCompatibiliRinnovoAsync(@base, tipoListino, idIscrizione);
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetComponentiPacchetto(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcComponentiPacchettoRequest request) {
            return base.Channel.GetComponentiPacchetto(@base, request);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetComponentiPacchettoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcComponentiPacchettoRequest request) {
            return base.Channel.GetComponentiPacchettoAsync(@base, request);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="wsListini.iElenchi_001")]
    public interface iElenchi_001 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetListini", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetListiniResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetListini", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetListiniResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorie", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorieResponse")]
        AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(AquardensUnitTest.wsListini.dcBaseRequest @base, System.Nullable<int> tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorie", ReplyAction="http://zitaca.com/gridservices/001/iElenchi_001/GetCategorieResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, System.Nullable<int> tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iElenchi_001Channel : AquardensUnitTest.wsListini.iElenchi_001, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iElenchi_001Client : System.ServiceModel.ClientBase<AquardensUnitTest.wsListini.iElenchi_001>, AquardensUnitTest.wsListini.iElenchi_001 {
        
        public iElenchi_001Client() {
        }
        
        public iElenchi_001Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iElenchi_001Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchi_001Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchi_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListini(@base, filter);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListiniAsync(@base, filter);
        }
        
        public AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(AquardensUnitTest.wsListini.dcBaseRequest @base, System.Nullable<int> tipo) {
            return base.Channel.GetCategorie(@base, tipo);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, System.Nullable<int> tipo) {
            return base.Channel.GetCategorieAsync(@base, tipo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices/001", ConfigurationName="wsListini.iGestione_001")]
    public interface iGestione_001 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/SetListino", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/SetListinoResponse")]
        AquardensUnitTest.wsListini.dcEsitoIdBox SetListino(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoCompleto listino, System.Nullable<bool> visibile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/001/iGestione_001/SetListino", ReplyAction="http://zitaca.com/gridservices/001/iGestione_001/SetListinoResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcEsitoIdBox> SetListinoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoCompleto listino, System.Nullable<bool> visibile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iGestione_001Channel : AquardensUnitTest.wsListini.iGestione_001, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iGestione_001Client : System.ServiceModel.ClientBase<AquardensUnitTest.wsListini.iGestione_001>, AquardensUnitTest.wsListini.iGestione_001 {
        
        public iGestione_001Client() {
        }
        
        public iGestione_001Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iGestione_001Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iGestione_001Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iGestione_001Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AquardensUnitTest.wsListini.dcEsitoIdBox SetListino(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoCompleto listino, System.Nullable<bool> visibile) {
            return base.Channel.SetListino(@base, listino, visibile);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcEsitoIdBox> SetListinoAsync(AquardensUnitTest.wsListini.dcBaseRequest @base, AquardensUnitTest.wsListini.dcListinoCompleto listino, System.Nullable<bool> visibile) {
            return base.Channel.SetListinoAsync(@base, listino, visibile);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="wsListini.iElenchi")]
    public interface iElenchi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListini", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(string sessionId, string impianto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListini", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(string sessionId, string impianto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListiniFiltered", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniFilteredResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito GetListiniFiltered(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetListiniFiltered", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetListiniFilteredResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniFilteredAsync(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListinoFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetCategorie", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetCategorieResponse")]
        AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(string sessionId, string impianto, System.Nullable<int> tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iElenchi/GetCategorie", ReplyAction="http://zitaca.com/gridservices/iElenchi/GetCategorieResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(string sessionId, string impianto, System.Nullable<int> tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iElenchiChannel : AquardensUnitTest.wsListini.iElenchi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iElenchiClient : System.ServiceModel.ClientBase<AquardensUnitTest.wsListini.iElenchi>, AquardensUnitTest.wsListini.iElenchi {
        
        public iElenchiClient() {
        }
        
        public iElenchiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iElenchiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iElenchiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetListini(string sessionId, string impianto) {
            return base.Channel.GetListini(sessionId, impianto);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniAsync(string sessionId, string impianto) {
            return base.Channel.GetListiniAsync(sessionId, impianto);
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito GetListiniFiltered(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListiniFiltered(sessionId, impianto, filter);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> GetListiniFilteredAsync(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListinoFilter filter) {
            return base.Channel.GetListiniFilteredAsync(sessionId, impianto, filter);
        }
        
        public AquardensUnitTest.wsListini.dcCategorieElencoEsito GetCategorie(string sessionId, string impianto, System.Nullable<int> tipo) {
            return base.Channel.GetCategorie(sessionId, impianto, tipo);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcCategorieElencoEsito> GetCategorieAsync(string sessionId, string impianto, System.Nullable<int> tipo) {
            return base.Channel.GetCategorieAsync(sessionId, impianto, tipo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://zitaca.com/gridservices", ConfigurationName="wsListini.iGestione")]
    public interface iGestione {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iGestione/AddListini", ReplyAction="http://zitaca.com/gridservices/iGestione/AddListiniResponse")]
        AquardensUnitTest.wsListini.dcListiniElencoEsito AddListini(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListino[] listini);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://zitaca.com/gridservices/iGestione/AddListini", ReplyAction="http://zitaca.com/gridservices/iGestione/AddListiniResponse")]
        System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> AddListiniAsync(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListino[] listini);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iGestioneChannel : AquardensUnitTest.wsListini.iGestione, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iGestioneClient : System.ServiceModel.ClientBase<AquardensUnitTest.wsListini.iGestione>, AquardensUnitTest.wsListini.iGestione {
        
        public iGestioneClient() {
        }
        
        public iGestioneClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iGestioneClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iGestioneClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iGestioneClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AquardensUnitTest.wsListini.dcListiniElencoEsito AddListini(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListino[] listini) {
            return base.Channel.AddListini(sessionId, impianto, listini);
        }
        
        public System.Threading.Tasks.Task<AquardensUnitTest.wsListini.dcListiniElencoEsito> AddListiniAsync(string sessionId, string impianto, AquardensUnitTest.wsListini.dcListino[] listini) {
            return base.Channel.AddListiniAsync(sessionId, impianto, listini);
        }
    }
}
